### ISSUE TITLE
brew install gazebo error in mac yosematic

### ISSUE THREAD

**Issue by chien800614** [scpeters/homebrew-gazebo#1]
ld: internal error: atom not found in symbolIndex(__ZNK6gazebo4math4Pose16CoordPositionSubERKS1_) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [gazebo/math/libgazebo_math.1.8.6.dylib] Error 1
make[1]: **\* [gazebo/math/CMakeFiles/gazebo_math.dir/all] Error 2
make: **\* [all] Error 2

**Comment by scpeters** [comment]
This is an old tap; please use `brew tap osrf/simulation`. I'm going to delete this formula since it's out of date.

**Comment by chien800614** [comment]
but why i can not install gazebo; i can only install gazebo4

**Comment by scpeters** [comment]
This is an old tap with old formulae that may interfere with the formulae in `osrf/simulation`. Please try the following:

```
brew untap scpeters/gazebo
brew tap osrf/simulation
brew install gazebo
```

**Comment by chien800614** [comment]
but now,  Error: No available formula for gazebo

**Comment by chien800614** [comment]
because i want to rosdep install --from-paths src --ignore-src --rosdistro indigo -y
i have already install gazebo4 but i still can not install gazebo. if i can brew install gazebo, rosdep install  will not be continue

**Comment by scpeters** [comment]
Can you also try `brew tap --repair`?

Can you provide a link to the instructions page you are following?

**Comment by chien800614** [comment]
yes, it work! Thank you!
